apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube-local.fullname" . }}
  labels:
    {{- include "sonarqube-local.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sonarqube-local.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sonarqube-local.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarqube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/system/status
              port: http
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /api/system/status
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 10
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
              subPath: data
            - name: sonarqube-data
              mountPath: /opt/sonarqube/extensions
              subPath: extensions
      volumes:
        - name: sonarqube-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "sonarqube-local.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
