apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "banking-platform.fullname" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "banking-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  environment: {{ .Values.environment | quote }}
